sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start
  - wget https://download.netbeans.org/netbeans/8.2/final/zip/netbeans-8.2-201609300101-javase.zip -O netbeans.zip
  - unzip -q netbeans.zip
    #- mvn -q dependency:get -Dartifact=junit:junit:4.8.2 -DrepoUrl=http://repo1.maven.org/maven2/
  # To reduce amout of log
  - cd maven-wrapper/ && mvn -q install && cd ..

script:
  - ant -Dnbplatform.nb82.netbeans.dest.dir=$PWD/netbeans -Dnbplatform.nb82.harness.dir=$PWD/netbeans/harness -Dfork=true test
